### PR TITLE
update: parse function type variable substringBeforeLast change subst…

### PR DESCRIPTION
**Pull request by denghuafeng**
fix: 
```HTML
stringRange:<li style="background: rgba(0, 0, 0, 0) none repeat scroll 0% 0%;">,</li>  
```
parsing error

### CODE REVIEW

**Comment by fivesmallq** [comment]
Thanks for the PR, Please add tests for this issue include success and fail.

**Comment by denghuafeng** [comment]
ok

**Comment by fivesmallq** [comment]
Looks Great! Thank you very much for the PR.

**Comment by fivesmallq** [comment]
@denghuafeng i deployed to the maven snapshots repositories. https://oss.sonatype.org/content/repositories/snapshots/im/nll/data/extractor/

you can use it like this:

```xml
<dependency>
    <groupId>im.nll.data</groupId>
    <artifactId>extractor</artifactId>
    <version>0.9.7-SNAPSHOT</version>
</dependency>
```

**Comment by denghuafeng** [comment]
so good!

**Pull request merged**
